# Generated by Django 2.0.1 on 2018-02-13 15:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import yamlfield.fields


class Migration(migrations.Migration):

    replaces = [('manager', '0001_initial'), ('manager', '0002_resource_uid'), ('manager', '0003_auto_20180108_2256'), ('manager', '0004_relationship_manager'), ('manager', '0005_auto_20180123_1306'), ('manager', '0006_auto_20180208_2128'), ('manager', '0007_auto_20180211_2210'), ('manager', '0008_auto_20180213_1040')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine', models.CharField(default='saltstack', max_length=32)),
                ('metadata', yamlfield.fields.YAMLField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=1)),
                ('metadata', yamlfield.fields.YAMLField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('kind', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=1)),
                ('metadata', yamlfield.fields.YAMLField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
                ('uid', models.CharField(max_length=511)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='manager.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='manager.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.Manager'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='RelationshipProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('manager.relationship',),
        ),
        migrations.AddField(
            model_name='resource',
            name='sources',
            field=models.ManyToManyField(related_name='resource_sources', through='manager.Relationship', to='manager.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='targets',
            field=models.ManyToManyField(related_name='resource_targets', through='manager.RelationshipProxy', to='manager.Resource'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manager.Manager'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
