# Generated by Django 2.0.1 on 2018-01-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
