# Generated by Django 2.0.1 on 2018-01-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_resource_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='link_from',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='link_to',
        ),
        migrations.AddField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='manager.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='manager.Resource'),
            preserve_default=False,
        ),
    ]
