# Generated by Django 2.0.1 on 2018-01-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180108_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.Manager'),
            preserve_default=False,
        ),
    ]
