# Generated by Django 2.0.1 on 2018-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_relationship_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uid',
            field=models.CharField(max_length=511),
        ),
    ]
