# Generated by Django 2.0.1 on 2018-02-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180123_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
    ]
