# Generated by Django 2.0.1 on 2018-02-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180208_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('manager.relationship',),
        ),
        migrations.AddField(
            model_name='resource',
            name='sources',
            field=models.ManyToManyField(related_name='resource_sources', through='manager.Relationship', to='manager.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='targets',
            field=models.ManyToManyField(related_name='resource_targets', through='manager.RelationshipProxy', to='manager.Resource'),
        ),
    ]
