from django.urls import path
from . import views
from .engine.hier_deploy import views as hier_deploy_views

app_name = 'inventory'
urlpatterns = [
    path('v1',
         views.InventoryListView.as_view(),
         name='inventory_list'),
    path('v1/inventory-create',
         hier_deploy_views.InventoryCreateView.as_view(),
         name='inventory_create'),
    path('v1/inventory-create/data.json',
         hier_deploy_views.InventoryCreateJSONView.as_view(),
         name='inventory_json_create'),
    path('v1/inventory-check',
         views.InventoryCheckView.as_view(),
         name='inventory_check'),
    path('v1/<inventory_name>',
         views.InventoryDetailView.as_view(),
         name='inventory_detail'),
    path('v1/<inventory_name>/sync',
         views.InventorySyncView.as_view(),
         name='inventory_sync'),
    path('v1/<inventory_name>/delete',
         views.InventoryDeleteView.as_view(),
         name='inventory_delete'),
    path('v1/<inventory_name>/data.json',
         views.InventoryDetailJSONView.as_view(),
         name='inventory_json_detail'),
    path('v1/<inventory_name>/create',
         views.ResourceCreateView.as_view(),
         name='resource_create'),
    path('v1/<inventory_name>/node-create',
         hier_deploy_views.NodeCreateView.as_view(),
         name='node_create'),
    path('v1/<inventory_name>/node/<node_name>',
         hier_deploy_views.NodeDetailView.as_view(),
         name='node_detail'),
    path('v1/<inventory_name>/node/<node_name>/update',
         hier_deploy_views.NodeUpdateView.as_view(),
         name='node_update'),
    path('v1/<inventory_name>/param-create',
         hier_deploy_views.ParamCreateView.as_view(),
         name='param_create'),
    path('v1/<inventory_name>/param/<param_name>/update',
         hier_deploy_views.ParamUpdateView.as_view(),
         name='param_update'),
    path('v1/<inventory_name>/param/<param_name>/delete',
         hier_deploy_views.ParamDeleteView.as_view(),
         name='param_delete'),
    path('v1/<inventory_name>/classify',
         views.ResourceClassifyView.as_view(),
         name='resource_classify'),
    path('v1/<inventory_name>/resource/<resource_name>',
         views.ResourceDetailView.as_view(),
         name='resource_detail'),
    path('v1/<inventory_name>/resource/<resource_name>/delete',
         views.ResourceDeleteView.as_view(),
         name='resource_delete'),
    path('v1/<inventory_name>/<resource_name>/data.json',
         views.ResourceDetailJSONView.as_view(),
         name='resource_json_detail'),
    path('v1/<inventory_name>/model/<form_name>/simple-generate',
         views.ClassGenerateView.as_view(),
         name='model_generate'),
    path('v1/<inventory_name>/model/<form_name>/wizard-generate',
         views.ClassGenerateWizardView.as_view(),
         name='model_generate_wizard'),

]
