# Generated by Django 2.1.1 on 2018-09-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='repository',
            name='engine',
            field=models.CharField(default='packer', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='repository.Repository'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
