# Generated by Django 2.1.1 on 2018-09-20 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=1)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='monitor.Resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='monitor.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('monitor.relationship',),
        ),
    ]
