# Generated by Django 2.1.1 on 2018-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_relationship_relationshipproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='sources',
            field=models.ManyToManyField(related_name='resource_sources', through='monitor.Relationship', to='monitor.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='targets',
            field=models.ManyToManyField(related_name='resource_targets', through='monitor.RelationshipProxy', to='monitor.Resource'),
        ),
    ]
