# Generated by Django 2.0.1 on 2018-02-08 21:21

from django.db import migrations, models
import django.db.models.deletion
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180202_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=511)),
                ('name', models.CharField(max_length=511)),
                ('kind', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=1)),
                ('metadata', yamlfield.fields.YAMLField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='resource',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor'),
        ),
    ]
