# Generated by Django 2.0.1 on 2018-02-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
