# Generated by Django 2.0.1 on 2018-02-13 08:44

from django.db import migrations
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cache',
            field=yamlfield.fields.YAMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='cache',
            field=yamlfield.fields.YAMLField(blank=True, null=True),
        ),
    ]
